# Generated by Django 4.1.5 on 2023-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='"D:\\photography\\IMG_20210919_183758.jpg"', upload_to='static/'),
        ),
    ]
