# Generated by Django 4.1.5 on 2023-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_user_image_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='D:\\photography\\IMG_20201102_180004890.jpg', upload_to='static/'),
        ),
    ]
