# Generated by Django 4.1.5 on 2023-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='"D:\\photography\\IMG_20201102_180004890.jpg"', upload_to='static/img'),
        ),
    ]
